version: '3'
services:
    web:
        build: .
        command: gunicorn cicd_app.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:12.2-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.db.dev
volumes:
    postgres_data:
