version: '3'
services:
  web:
    build:
      dockerfile: docker/web/Dockerfile
      context: .
    image: cicd-app-web:0.0.1.dev0
    entrypoint:
      "/app/entrypoint.sh"
    command: sh -c "gunicorn cicd_app.base.wsgi:application --workers 2 --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    links:
      - db
  db:
      image: postgres:12.2-alpine
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data/
      env_file:
        - ./.env.db
  nginx:
      build: docker/nginx
      volumes:
        - static_volume:/app/static
        - media_volume:/app/media
      ports:
        - "1337:80"
      depends_on:
        - web

volumes:
    pgdata:
    static_volume:
    media_volume:
