version: '3'
services:
    web:
        build: docker/Dockerfile.prod
        entrypoint:
            "/app/entrypoint.sh"
        command: sh -c "cd /app/cicd_app; gunicorn --env DJANGO_SETTINGSMODULE=settings.production base.wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        env_file:
            - ./.env.prod
        depends_on:
            - db
        links:
            - db
    db:
        image: postgres:12.2-alpine
        ports:
          - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data/
        env_file:
            - ./.env.db
volumes:
    pgdata:
