[tool.poetry]
name = "cicd_app"
version = "0.0.1"
description = ""
authors = ["Rio Matsuoka <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.4"
djangorestframework = "^3.11.0"
cryptography = "^2.8"
djangorestframework-jwt = "^1.11.0"
django-cors-headers = "^3.2.1"
psycopg2 = "^2.8.4"
gunicorn = "^20.0.4"

[tool.poetry.dev-dependencies]
coverage = "^5.0.3"
pytest = "^5.3.5"
django-debug-toolbar = "^2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
