#!/usr/bin/env python3

from .base import *

# secure connection
# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SECURE_HSTS_SECONDS = 3600
# SECURE_REFERRER_POLICY = []
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
